name: Build and Push Backstage Docker Image

on:
  push:
    branches:
      - master

env:
  TAG: docker.io/brucorreia/backstage:1.0.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd casume
        yarn install --immutable
        yarn tsc
        yarn build:backend

    - name: Log in to Docker Hub (ou GitHub Container Registry)
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build
      run: |
        pwd
        ls -l packages/backend/dist
        docker image build . -f packages/backend/Dockerfile --tag $TAG

    - name: Push Docker image
      run: |
        docker push $TAG