name: Build and Push Backstage Docker Image

on:
  push:
    branches:
      - master

env:
  REGISTRY_URL: docker.io
  IMAGE_NAME: brucorreia/backstage
  TAG: backstage:1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
          yarn install --immutable
          yarn tsc
          yarn build:backend

    - name: Log in to Docker Hub (ou GitHub Container Registry)
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    
    - name: Docker Build
      run: |
        docker image build . -f packages/backend/Dockerfile --tag $TAG

    - name: Push Docker image
      run: |
        docker push $REGISTRY_URL/$IMAGE_NAME:$TAG